version: '3.8'

services:
  uv-calculator-api:
    build: .
    container_name: uv-calculator-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs